### PR TITLE
Fixed multipart about #6

### PR DESCRIPTION
**Pull request by NobukazuHanada**
fixed about https://github.com/evancz/elm-http/issues/6

### CODE REVIEW

**Comment by Dobiasd** [comment]
@amcvega just created [a similar pull request](https://github.com/evancz/elm-http/pull/13), but with one more change

```
return { ctor: 'BodyFormData', formData: formData };
```

It would be great if you two could connect to resolve this difference.

**Comment by evancz** [comment]
I went for the other one. I think this change was slightly off in that it used the `'FormData'` constructor instead of `'BodyFormData'`. Thanks for the fix though!

**Comment by NobukazuHanada** [comment]
I am sorry I created a similar pull request.  In a different way I will contribute continuously.

**Comment by evancz** [comment]
Do not worry! You did everything right in this PR! Your PR came in way before the other one, and it largely fixed the issue. 

In this case, I failed to get a timely response to your issue to fix one minor piece. This is part of a larger pattern of having too many issues to review per day, and I am working on that. So again, you did everything right!

So thanks for the PR and I hope we did not make this a scary process. I am trying to get the processes in place so we can do better next time!

**Comment by evancz** [comment]
Thanks @Dobiasd for pointing the connection here. This kind of curation is extraordinarily helpful!

**Pull request closed without merging**
