### PR TITLE
Add the ability to use withCredentials for CORS and cookies in the Settings

### PR DESCRIPTION
**Pull request by yogsototh**

### CODE REVIEW

**Comment by jazmit** [comment]
+1 This is needed

**Comment by jazmit** [comment]
Unfortunately this causes my app to crash with 'setting is not defined' when I patch it in place of the official http library... I'll do some poking around and see if I can fix it.

**Comment by jazmit** [comment]
Unfortunately this causes my app to crash with 'setting is not defined'.  I think you meant 'settings?'

**Comment by jazmit** [comment]
I've now tested this change and it works fine with `setting` changed to `settings` in Http.js.  Would be nice to have this merged into master as I'm relying on it for a small production app.

**Comment by yogsototh** [comment]
@jazmit Thanks!

**Comment by jazmit** [comment]
@evancz Any chance of merging this before the next release?

**Comment by codedmart** [comment]
@evancz Any thoughts on this? Is there anything I can do to help move this along?

**Comment by codedmart** [comment]
I can confirm that withCredentials works great, but this PR will not work until `if (setting.withCredentials) {` isn't changed to `if (settings.withCredentials) {`. @yogsototh can you make that change. Then can we get this merged in @evancz? I will gladly grab @yogsototh's changes and fix that one typo if need be.

**Comment by yogsototh** [comment]
I am out of m'y computer reach this week. @codedmart do mind to make the fix for me? Thanks!

**Comment by evancz** [comment]
I'll bring this in for the next release. 0.16 requires that everything gets bumped, so I'll be able to get to it in the next week or so. Sorry for the long delay here!

**Comment by codedmart** [comment]
@evancz If @yogsototh has not been able to make the update before you bring this in I can do a new PR or I can do a new PR now if that would be better. I can't edit this PR.

@evancz Thanks for all your hard work.

**Comment by evancz** [comment]
Thanks for the PR and for checking to make sure it works!

**Pull request merged**
