### PR TITLE
Add put function for convenience

### PR DESCRIPTION
**Pull request by strickinato**
Putting should be as simple as GET and POST. I needed to submit a PUT for NRI prod and it took more work than I'd hope to write out the Http.send ensuring that all settings were right.

### CODE REVIEW

**Comment by codedmart** [comment]
@strickinato I think we should have a delete as well, and possibly a patch, but I don't use patch much.

**Comment by evancz** [comment]
Looks good to me, thanks!

**Comment by evancz** [comment]
Why do you have a `Json.Decoder` as an argument? Is it common that you put something and get a response back with JSON in it?

**Comment by evancz** [comment]
@strickinato, why do you have a `Json.Decoder` as an argument? Is it common that you put something and get a response back with JSON in it?

**Comment by evancz** [comment]
I don't really know what [this](http://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something) is saying exactly, but it looks like you can have a body, and that the body is potentially JSON depending on the content-type header.

I don't really know what the 4th scenario means for us though. It looks like that'd definitely not return JSON.

How can we change the API to account for all these scenarios? Is it related to #12?

**Pull request merged**
