### PR TITLE
Http.get sets desiredResponseType to JSON

### PR DESCRIPTION
**Pull request by antalk2**
When the page is loaded from `file://...` this avoids firefox error "not well-formed" for "file.json" in same directory

### CODE REVIEW

**Comment by evancz** [comment]
I think this makes sense. @rtfeldman, can you confirm that this is a desirable default? (No worries if not, it's just something where a second LGTM would be comforting :P)

@antalk2, do you mind making something like this:

``` elm
jsonSettings : Settings
jsonSettings =
  { defaultSettings |
      desiredResponseType = Just "application/json"
  }
```

Right below the definition of `handleResponse` and use it in both `get` and `post`? Do not publicly expose it though.

My main worry is that this'll do something unexpected that wasn't happening before, so I'd want to know what browsers and OSes you tested this on.

**Comment by rtfeldman** [comment]
:+1: and a further :+1: for @evancz's suggestions of creating `jsonSettings` and using it in both `get` and `post`!

**Comment by antalk2** [comment]
> @antalk2, do you mind making something like this:

ok, did it https://github.com/antalk2/elm-http/commit/ca2b256fd24ae0d7d5dc39ea175e8b670fe40aff

> My main worry is that this'll do something unexpected that wasn't happening before, so I'd want to
> know what browsers and OSes you tested this on.

See https://github.com/antalk2/elm-http-test, included test results in README.md

In short:
- The firefox error "not well-formed" I mentioned originally apparently does not preclude loading
  and decoding a JSON file from `file://...`, thus the proposed change is not necessary for allowing this.
- Found no effect of desiredResponseType on the request header. I expected it to show up in
  the `Accept:` field.
- Found no other effect (neither good, nor bad) of setting desiredResponseType with firefox 42.0 (under Ubuntu, Windows XP and Windows 7) or chromium-browser (Version 45.0.2454.101 Ubuntu 14.04) (For Windows only the `file://` case was tested,  `http://` was not)
- For `post`, setting the response content type to  "application/json" or "text/plain" in `config.php`,
  although it does appear in the response header (with Apache), it seems to have no effect on
  receiving and decoding the answer (which is successful with either).

**Comment by antalk2** [comment]
Some source suggest that Opera and IE does not have
`XMLHttpRequest.overrideMimeType` (which is used if `desiredResponseType` is set)
- http://stackoverflow.com/questions/4542992/setting-overridemimetypeapplication-json-with-prototype-js

"you should be aware that overrideMimeType is not available in IE or
Opera. If you still want to use it you should ensure that you check
from the presence of the method on the XMLHttpResponse object."
- https://code.google.com/p/geoxml3/issues/detail?id=78
  
  Internet Explorer 10 does not have `req.overrideMimeType`

So it is probably best to not set `desiredResponseType` without 
checking on the javascript side if `XMLHttpRequest.overrideMimeType` is actually
supported.

**Pull request closed without merging**
